ft_printf: ft_printf() family
ft_printf() family
Replicate behaviour of printf(3) functions.
Functions
int ft_printf (const char *format,...)
Replicates behaviour of printf(3).
int ft_dprintf (int fd, const char *format,...)
Replicates behaviour of dprintf(3).
int ft_vprintf (const char *format, va_list ap)
Replicates behaviour of vprintf(3).
int ft_vdprintf (int fd, const char *format, va_list ap)
Replicates behaviour of vdprintf(3).
int ft_sprintf (char *str, const char *format,...)
Replicates behaviour of sprintf(3).
int ft_vsprintf (char *str, const char *format, va_list ap)
Replicates behaviour of vsprintf(3).
int ft_snprintf (char *str, size_t size, const char *format,...)
Replicates behaviour of snprintf(3).
int ft_vsnprintf (char *str, size_t size, const char *format, va_list ap)
Replicates behaviour of vsnprintf(3).
int ft_asprintf (char **ret, const char *format,...)
Replicates behaviour of asprintf(3).
int ft_vasprintf (char **ret, const char *format, va_list ap)
Replicates behaviour of vasprintf(3).
Detailed Description
Replicate behaviour of printf(3) functions.
Support standard field values and combination thereof (where applicable):
flags: #, 0, , -, +
width and precision, including * options
length: hh, h, l, ll, L, j
type: c, s, p, %, d, i, o, u, x, X, f
Custom specifications:
b type to print in binary format (supports same parameters as i type)
color support
cyan
red
green
yellow
blue
magenta
To print in color
ft_printf("{red}Color-print. {eoc}Normal print.");
See also
https://en.wikipedia.org/wiki/Printf_format_string
https://linux.die.net/man/3/printf
Function Documentation
ft_asprintf()
int ft_asprintf (char ** ret, const char * format, ...)
Replicates behaviour of asprintf(3).
Parameters
[out] ret Pointer that will be set to a buffer sufficiently large to hold the formatted string. This pointer should be passed to free(3) to release the allocated storage when it is no longer needed.
[in] format Format string that specifies how subsequent arguments are converted for output
[in] ... Variadic arguments
Returns
Number of characters printed or -1 if an error occurs. Additionaly, in case of an error, *ret is set to be NULL and errno is set to ENOMEM (memory allocation error), EINVAL (invalid format placeholder specification), ENOTSUP (type field value not supported).
References ft_vasprintf().
ft_dprintf()
int ft_dprintf (int fd, const char * format, ...)
Replicates behaviour of dprintf(3).
Parameters
[in] fd File descriptor where to print output.
[in] format Format string that specifies how subsequent arguments are converted for output
[in] ... Variadic arguments
Returns
Number of characters printed or -1 if an error occurs. Additionaly, in case of an error, errno is set to ENOMEM (memory allocation error), EINVAL (invalid format placeholder specification), ENOTSUP (type field value not supported).
References ft_vdprintf().
ft_printf()
int ft_printf (const char * format, ...)
Replicates behaviour of printf(3).
Parameters
[in] format Format string that specifies how subsequent arguments are converted for output
[in] ... Variadic arguments
Returns
Number of characters printed or -1 if an error occurs. Additionaly, in case of an error, errno is set to ENOMEM (memory allocation error), EINVAL (invalid format placeholder specification), ENOTSUP (type field value not supported) or other values set by write(2).
References ft_vprintf().
ft_snprintf()
int ft_snprintf (char * str, size_t size, const char * format, ...)
Replicates behaviour of snprintf(3).
Parameters
[in] str String where to print output.
[in] size Size of the string (at most size - 1 characters are printed and, unless size is 0, the string is always null-terminated).
[in] format Format string that specifies how subsequent arguments are converted for output
[in] ... Variadic arguments
Returns
Number of characters printed if size were unlimited (not including the final \0) or -1 if an error occurs. Additionaly, in case of an error, errno is set to ENOMEM (memory allocation error), EINVAL (invalid format placeholder specification), ENOTSUP (type field value not supported).
References ft_vsnprintf().
ft_sprintf()
int ft_sprintf (char * str, const char * format, ...)
Replicates behaviour of sprintf(3).
Parameters
[in] str String where to print output.
[in] format Format string that specifies how subsequent arguments are converted for output
[in] ... Variadic arguments
Returns
Number of characters printed or -1 if an error occurs. Additionaly, in case of an error, errno is set to ENOMEM (memory allocation error), EINVAL (invalid format placeholder specification), ENOTSUP (type field value not supported).
References ft_vsnprintf().
ft_vasprintf()
int ft_vasprintf (char ** ret, const char * format, va_list ap)
Replicates behaviour of vasprintf(3).
Parameters
[out] ret Pointer that will be set to a buffer sufficiently large to hold the formatted string. This pointer should be passed to free(3) to release the allocated storage when it is no longer needed.
[in] format Format string that specifies how subsequent arguments are converted for output
[in] ap A variable used by stdarg(3) to step through a list of variadic arguments.
Returns
Number of characters printed or -1 if an error occurs. Additionaly, in case of an error, *ret is set to be NULL and errno is set to ENOMEM (memory allocation error), EINVAL (invalid format placeholder specification), ENOTSUP (type field value not supported).
References ft_vsnprintf(), and ft_vsprintf().
ft_vdprintf()
int ft_vdprintf (int fd, const char * format, va_list ap)
Replicates behaviour of vdprintf(3).
Parameters
[in] fd File descriptor where to print output
[in] format Format string that specifies how subsequent arguments are converted for output
[in] ap A variable used by stdarg(3) to step through a list of variadic arguments.
Returns
Number of characters printed or -1 if an error occurs. Additionaly, in case of an error, errno is set to ENOMEM (memory allocation error), EINVAL (invalid format placeholder specification), ENOTSUP (type field value not supported) or other values set by write(2) (e.g. due to an invalid file descriiptor).
References ft_vprintf().
ft_vprintf()
int ft_vprintf (const char * format, va_list ap)
Replicates behaviour of vprintf(3).
Parameters
[in] format Format string that specifies how subsequent arguments are converted for output
[in] ap A variable used by stdarg(3) to step through a list of variadic arguments.
Returns
Number of characters printed or -1 if an error occurs. Additionaly, in case of an error, errno is set to ENOMEM (memory allocation error), EINVAL (invalid format placeholder specification), ENOTSUP (type field value not supported) or other values set by write(2) (e.g. due to an invalid file descriiptor).
ft_vsnprintf()
int ft_vsnprintf (char * str, size_t size, const char * format, va_list ap)
Replicates behaviour of vsnprintf(3).
Parameters
[in] str String where to print output.
[in] size Size of the string (at most size - 1 characters are printed and, unless size is 0, the string is always null-terminated).
[in] format Format string that specifies how subsequent arguments are converted for output
[in] ap A variable used by stdarg(3) to step through a list of variadic arguments.
Returns
Number of characters printed if size were unlimited (not including the final \0) or -1 if an error occurs. Additionaly, in case of an error, errno is set to ENOMEM (memory allocation error), EINVAL (invalid format placeholder specification), ENOTSUP (type field value not supported).
References ft_vprintf().
ft_vsprintf()
int ft_vsprintf (char * str, const char * format, va_list ap)
Replicates behaviour of vsprintf(3).
Parameters
[in] str String where to print output.
[in] format Format string that specifies how subsequent arguments are converted for output
[in] ap A variable used by stdarg(3) to step through a list of variadic arguments.
Returns
Number of characters printed or -1 if an error occurs. Additionaly, in case of an error, errno is set to ENOMEM (memory allocation error), EINVAL (invalid format placeholder specification), ENOTSUP (type field value not supported).
References ft_vprintf().